services:
  pioloop-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pioloop-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://pioloop-api:64604/api
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - pioloop-api_default

networks:
  pioloop-api_default:
    external: true 